site_name: Documentation for Apicart.net
docs_dir: docs

theme:
   name: 'material'
   palette:
      primary: 'deep purple'
      accent: 'deep purple'

markdown_extensions:
   - admonition
   - codehilite
   - footnotes
   - pymdownx.critic
   - pymdownx.inlinehilite
   - pymdownx.superfences
   - pymdownx.tilde
   - pymdownx.tasklist:
      custom_checkbox: true
   - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
   - toc:
      permalink: true

nav:
   - Introduction: index.md
   - 'Another page': another-page.md
   - 'Next another page': next-another-page.md
